services:
  analytics-service:
    build:
      context: .
    image: analytics-service:latest
    container_name: analytics-service-app
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal
networks:
  internal :
    external: true

