### POST request to create Patient
POST http://localhost:8080/patients
Content-Type: application/json

{
  "name": "John doe",
  "email": "test@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-09-03"
}

###