version: "3.9"

services:
  app:
    build:
      context: .
    image: billing-service
    container_name: billing-service-app
    ports:
      - "8081:8081"
      - "9090:9090"
    networks:
      - internal
networks:
    internal:
